// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecurityReport.Infrastructure.Persistence;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(SecurityReportDbContext))]
    [Migration("20260910193124_AddAIClassificationFields")]
    partial class AddAIClassificationFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SecurityReport.Domain.Entities.ActoInseguro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaIdentificacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ReporteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ReporteId");

                    b.ToTable("Actos");
                });

            modelBuilder.Entity("SecurityReport.Domain.Entities.AnalisisIA", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMensaje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Justificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NivelRiesgo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prioridad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecomendacionesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReporteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResultadoJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoRiesgo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReporteId");

                    b.ToTable("Analisis");
                });

            modelBuilder.Entity("SecurityReport.Domain.Entities.Area", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("SecurityReport.Domain.Entities.CondicionInsegura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaIdentificacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ReporteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ReporteId");

                    b.ToTable("Condiciones");
                });

            modelBuilder.Entity("SecurityReport.Domain.Entities.EstadoReporte", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EstadosReporte");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Nombre = "Abierto"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Nombre = "EnProgreso"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Nombre = "Cerrado"
                        });
                });

            modelBuilder.Entity("SecurityReport.Domain.Entities.Evidencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReporteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ReporteId");

                    b.ToTable("Evidencias");
                });

            modelBuilder.Entity("SecurityReport.Domain.Entities.InformeIA", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Informes");
                });

            modelBuilder.Entity("SecurityReport.Domain.Entities.LogAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EntidadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LogsAuditoria");
                });

            modelBuilder.Entity("SecurityReport.Domain.Entities.NormativaSGSST", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Normativas");
                });

            modelBuilder.Entity("SecurityReport.Domain.Entities.Permiso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Permisos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1a1a1a1-0000-0000-0000-000000000001"),
                            Codigo = "crear_reporte",
                            Nombre = "Crear Reportes"
                        },
                        new
                        {
                            Id = new Guid("a1a1a1a1-0000-0000-0000-000000000002"),
                            Codigo = "editar_reporte",
                            Nombre = "Editar Reportes"
                        },
                        new
                        {
                            Id = new Guid("a1a1a1a1-0000-0000-0000-000000000003"),
                            Codigo = "eliminar_reporte",
                            Nombre = "Eliminar Reportes"
                        },
                        new
                        {
                            Id = new Guid("a1a1a1a1-0000-0000-0000-000000000004"),
                            Codigo = "ver_dashboard",
                            Nombre = "Ver Dashboard"
                        },
                        new
                        {
                            Id = new Guid("a1a1a1a1-0000-0000-0000-000000000005"),
                            Codigo = "gestionar_usuarios",
                            Nombre = "Gestionar Usuarios"
                        },
                        new
                        {
                            Id = new Guid("a1a1a1a1-0000-0000-0000-000000000006"),
                            Codigo = "ver_reportes",
                            Nombre = "Ver Reportes otros usuarios"
                        },
                        new
                        {
                            Id = new Guid("a1a1a1a1-0000-0000-0000-000000000007"),
                            Codigo = "generar_plan_ia",
                            Nombre = "Generar Plan de Acción con IA"
                        },
                        new
                        {
                            Id = new Guid("a1a1a1a1-0000-0000-0000-000000000008"),
                            Codigo = "acceder_administracion",
                            Nombre = "Acceder a Administración"
                        });
                });

            modelBuilder.Entity("SecurityReport.Domain.Entities.Reporte", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EstadoReporteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaReporte")
                        .HasColumnType("datetime2");

                    b.Property<string>("NivelReportadoUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonasAfectadas")
                        .HasColumnType("int");

                    b.Property<string>("PlanAccionJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReportadoPorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("TieneTestigos")
                        .HasColumnType("bit");

                    b.Property<Guid?>("TipoReporteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("EstadoReporteId");

                    b.HasIndex("FechaReporte");

                    b.HasIndex("ReportadoPorId");

                    b.HasIndex("TipoReporteId");

                    b.ToTable("Reportes");
                });

            modelBuilder.Entity("SecurityReport.Domain.Entities.RiesgoRepetitivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FirstDetected")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastDetected")
                        .HasColumnType("datetime2");

                    b.Property<string>("NivelRiesgo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ocurrencias")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RiesgosRepetitivos");
                });

            modelBuilder.Entity("SecurityReport.Domain.Entities.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Nombre = "ResponsableSST"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Nombre = "Colaborador"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Nombre = "Operario"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Nombre = "Supervisor"
                        });
                });

            modelBuilder.Entity("SecurityReport.Domain.Entities.RolPermiso", b =>
                {
                    b.Property<Guid>("RolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermisoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RolId", "PermisoId");

                    b.HasIndex("PermisoId");

                    b.ToTable("RolesPermiso");

                    b.HasData(
                        new
                        {
                            RolId = new Guid("44444444-4444-4444-4444-444444444444"),
                            PermisoId = new Guid("a1a1a1a1-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RolId = new Guid("55555555-5555-5555-5555-555555555555"),
                            PermisoId = new Guid("a1a1a1a1-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RolId = new Guid("55555555-5555-5555-5555-555555555555"),
                            PermisoId = new Guid("a1a1a1a1-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RolId = new Guid("55555555-5555-5555-5555-555555555555"),
                            PermisoId = new Guid("a1a1a1a1-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            RolId = new Guid("55555555-5555-5555-5555-555555555555"),
                            PermisoId = new Guid("a1a1a1a1-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            RolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermisoId = new Guid("a1a1a1a1-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermisoId = new Guid("a1a1a1a1-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermisoId = new Guid("a1a1a1a1-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermisoId = new Guid("a1a1a1a1-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            RolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermisoId = new Guid("a1a1a1a1-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            RolId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermisoId = new Guid("a1a1a1a1-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            RolId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermisoId = new Guid("a1a1a1a1-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RolId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermisoId = new Guid("a1a1a1a1-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RolId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermisoId = new Guid("a1a1a1a1-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RolId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermisoId = new Guid("a1a1a1a1-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            RolId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermisoId = new Guid("a1a1a1a1-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            RolId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermisoId = new Guid("a1a1a1a1-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            RolId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermisoId = new Guid("a1a1a1a1-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            RolId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermisoId = new Guid("a1a1a1a1-0000-0000-0000-000000000008")
                        });
                });

            modelBuilder.Entity("SecurityReport.Domain.Entities.TipoReporte", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TiposReporte");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1d1d1d1-d1d1-d1d1-d1d1-d1d1d1d1d1d1"),
                            Descripcion = "Situación o factor físico del entorno que puede causar un accidente",
                            Nombre = "Condición Insegura"
                        },
                        new
                        {
                            Id = new Guid("d2d2d2d2-d2d2-d2d2-d2d2-d2d2d2d2d2d2"),
                            Descripcion = "Comportamiento o acción de una persona que aumenta el riesgo de accidente",
                            Nombre = "Acto Inseguro"
                        },
                        new
                        {
                            Id = new Guid("d3d3d3d3-d3d3-d3d3-d3d3-d3d3d3d3d3d3"),
                            Descripcion = "Evento que resultó o pudo resultar en lesión, daño o pérdida",
                            Nombre = "Incidente / Accidente"
                        });
                });

            modelBuilder.Entity("SecurityReport.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SecurityReport.Domain.Entities.ActoInseguro", b =>
                {
                    b.HasOne("SecurityReport.Domain.Entities.Reporte", "Reporte")
                        .WithMany("Actos")
                        .HasForeignKey("ReporteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reporte");
                });

            modelBuilder.Entity("SecurityReport.Domain.Entities.AnalisisIA", b =>
                {
                    b.HasOne("SecurityReport.Domain.Entities.Reporte", "Reporte")
                        .WithMany("Analisis")
                        .HasForeignKey("ReporteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reporte");
                });

            modelBuilder.Entity("SecurityReport.Domain.Entities.CondicionInsegura", b =>
                {
                    b.HasOne("SecurityReport.Domain.Entities.Reporte", "Reporte")
                        .WithMany("Condiciones")
                        .HasForeignKey("ReporteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reporte");
                });

            modelBuilder.Entity("SecurityReport.Domain.Entities.Evidencia", b =>
                {
                    b.HasOne("SecurityReport.Domain.Entities.Reporte", "Reporte")
                        .WithMany("Evidencias")
                        .HasForeignKey("ReporteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reporte");
                });

            modelBuilder.Entity("SecurityReport.Domain.Entities.Reporte", b =>
                {
                    b.HasOne("SecurityReport.Domain.Entities.Area", "Area")
                        .WithMany("Reportes")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecurityReport.Domain.Entities.EstadoReporte", "EstadoReporte")
                        .WithMany()
                        .HasForeignKey("EstadoReporteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecurityReport.Domain.Entities.Usuario", "ReportadoPor")
                        .WithMany("Reportes")
                        .HasForeignKey("ReportadoPorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecurityReport.Domain.Entities.TipoReporte", "TipoReporte")
                        .WithMany()
                        .HasForeignKey("TipoReporteId");

                    b.Navigation("Area");

                    b.Navigation("EstadoReporte");

                    b.Navigation("ReportadoPor");

                    b.Navigation("TipoReporte");
                });

            modelBuilder.Entity("SecurityReport.Domain.Entities.RolPermiso", b =>
                {
                    b.HasOne("SecurityReport.Domain.Entities.Permiso", "Permiso")
                        .WithMany("RolesPermiso")
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecurityReport.Domain.Entities.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SecurityReport.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("SecurityReport.Domain.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SecurityReport.Domain.Entities.Area", b =>
                {
                    b.Navigation("Reportes");
                });

            modelBuilder.Entity("SecurityReport.Domain.Entities.Permiso", b =>
                {
                    b.Navigation("RolesPermiso");
                });

            modelBuilder.Entity("SecurityReport.Domain.Entities.Reporte", b =>
                {
                    b.Navigation("Actos");

                    b.Navigation("Analisis");

                    b.Navigation("Condiciones");

                    b.Navigation("Evidencias");
                });

            modelBuilder.Entity("SecurityReport.Domain.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SecurityReport.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Reportes");
                });
#pragma warning restore 612, 618
        }
    }
}
