// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace SecurityReport.Infrastructure.Migrations
{
    public partial class InitialCreate : Migration
    {
    }
}
